export const environment = {
  BASE_URL_BE: "http://localhost:5000",
  REACT_APP_LOCAL_STORE_TOKEN_NAME: "vantai",
  BASE_URL_BE_IMAGE: "http://localhost:5000/Images/",
};

export const keyMap = {
  EN: "EN",
  VI: "VI",
  ADMIN: "ADMIN",
  SUPPLIER: "SUPPLIER",
  USER: "USER",
  MALE: "MALE",
  FEMALE: "FEMALE",
};

export const categoryId = {
  DIENTU: "DIENTU",
  THOITRANG: "THOITRANG",
  GIADUNG: "GIADUNG",
  VATDUNG: "VATDUNG",
};

export const transactionType = {
  CHOXACNHAN_CHUATHANHTOAN: "CHOXACNHAN_CHUATHANHTOAN",
  CHOXACNHAN_DATHANHTOAN: "CHOXACNHAN_DATHANHTOAN",
  CHOLAYHANG_DATHANHTOAN: "CHOLAYHANG_DATHANHTOAN",
  CHOLAYHANG_CHUATHANHTOAN: "CHOLAYHANG_CHUATHANHTOAN",
  DANGSHIP_DATHANHTOAN: "DANGSHIP_DATHANHTOAN",
  DANGSHIP_CHUATHANHTOAN: "DANGSHIP_CHUATHANHTOAN"
}


export const notifyTitleId = {
  DON_HANG_MOI: "DON_HANG_MOI",
  GIAO_HANG_THANH_CONG: "GIAO_HANG_THANH_CONG",
  DON_HANG_DUOC_XAC_NHAN: "DON_HANG_DUOC_XAC_NHAN",
  DON_HANG_DANG_DUOC_GIAO: "DON_HANG_DANG_DUOC_GIAO",
  DON_HANG_BI_HUY: "DON_HANG_BI_HUY",
  HE_THONG: "HE_THONG",
}

export const voucherTypeId = {

  VANCHUYEN: "VANCHUYEN",
  GIAMGIA: "GIAMGIA",
  VOUCHERSHOP: "VOUCHERSHOP",
}